openai:
  key: ${OPENAI_KEY}
  gpt:
    url: ${OPENAI_GPT_URL}
    model: ${OPENAI_GPT_MODEL}
  whisper:
    url: ${OPENAI_WHISPER_URL}

coolsms:
  key: ${COOLSMS-KEY}
  secret-key: ${COOLSMS-SECRET-KEY}
  domain: ${COOLSMS-DOMAIN}
  calling-number: ${COOLSMS-CALLING-NUMBER}
